package com.github.akinaru.roboticbuttonpusher.model;

/**
 * Created by akinaru on 02/06/16.
 */
public enum ButtonPusherError {
    SCAN_TIMEOUT,
    CONNECTION_TIMEOUT,
    PUSH_FAILURE,
    SET_PASSWORD_TIMEOUT,
    SET_MESSAGE_TIMEOUT,
    NOTIFICATION_TIMEOUT,
    ASSOCIATION_FAILURE,
    SET_KEYS_TIMEOUT,
    SET_KEYS_FAILURE,
    SET_PASSWORD_FAILURE,
    BLUETOOTH_STATE_TIMEOUT,
    DISASSOCIATE_FAILURE, DISASSOCIATE_TIMEOUT,
    SET_MESSAGE_FAILURE
}
